In [2]:
import numpy as np
A= np.array([[2,3,5],[3,4,7]])
B=np.array([[-2,3],[4,8],[-9,5]])
print(A)
print(B)
print("AB =",np.dot(A,B))
print("BA = ",np.dot(B,A))

[[2 3 5]
 [3 4 7]]
[[-2  3]
 [ 4  8]
 [-9  5]]
AB = [[-37  55]
 [-53  76]]
BA =  [[  5   6  11]
 [ 32  44  76]
 [ -3  -7 -10]]


In [7]:
import numpy as np
A=np.array([[1,3],[5,7]])
B=np.array([[4,-6],[-8,12]])
detA=np.linalg.det(A)
Ainv=np.linalg.inv(A)
print("Dinh thuc detA = ",detA)
print("Ma tran nghich dao cua detA = ",Ainv)
I=np.dot(A,Ainv)
print(I)
detB=np.linalg.det(B)
print(B)

Dinh thuc detA =  -7.999999999999998
Ma tran nghich dao cua detA =  [[-0.875  0.375]
 [ 0.625 -0.125]]
[[ 1.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00]]
[[ 4 -6]
 [-8 12]]
