In [ ]:
0.1.1 1. Doing linear algebra with NumPy arrays:

In [1]:
import numpy as np

In [ ]:
1.1. Vectors:

In [2]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [4]:
x + y

array([ 3,  7, 11])

In [5]:
x-y

array([-1, -1, -1])

In [ ]:
The following operations are possible in NumPy but not in linear algebra:

In [6]:
x * y

array([ 2, 12, 30])

In [7]:
x/y

array([0.5       , 0.75      , 0.83333333])

In [ ]:
Internal product with dot():

In [8]:
np.dot(x,y)

44

In [9]:
x.dot(y)

44

In [10]:
y.dot(x)

44

In [11]:
np.sum(x*y)

44

In [ ]:
1.2. Creating matrices:

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.seed(222)
np.random.random((2,2))

array([[0.52602843, 0.68531719],
       [0.83567419, 0.65376526]])

In [15]:
np.random.seed(111)
np.random.randn(2,2)

array([[-1.13383833,  0.38431919],
       [ 1.49655378, -0.3553823 ]])

In [16]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
1.3. Matrix operations: Matrix addition, subtraction and multiplication:


In [17]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])

In [18]:
m1+m2

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
m1-m2

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [20]:
np.transpose(m2)

array([[6, 3],
       [5, 2],
       [4, 1]])

In [ ]:
Matrix multiplication with dot():


In [21]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

In [22]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [23]:
y.dot(x)[0,0]

44

In [24]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [ ]:
The following operations are possible in NumPy but not in linear algebra:

In [25]:
m1 * m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [26]:
m1/m2

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

In [ ]:
Operations involving matrix and scalar:

In [27]:
m = np.array([[1, 2],[3, 4]])

In [28]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [29]:
m/2

array([[0.5, 1. ],
       [1.5, 2. ]])

1.4. Inverse matrix and system of linear equations: Calculating the inverse matrix:

In [30]:
m = np.array([[1, 2],[3, 4]])
minv = np.linalg.inv(m)
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [32]:
mres = np.dot(m, minv)
np.round(mres,2)

array([[1., 0.],
       [0., 1.]])

System of linear equations (number of equations = number of unknowns)

In [33]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)
print(np.dot(Ainv,b))

[[2.85714286]
 [1.96428571]]


In [34]:
np.linalg.solve(A, b)

array([[2.85714286],
       [1.96428571]])