In [9]:
import numpy as np

In [1]:
a = [1, 2, 3]

In [6]:
a+a

[1, 2, 3, 1, 2, 3]

In [7]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
b = np.array([1, 2, 3])

In [11]:
b+3

array([4, 5, 6])

In [12]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
1.2. ‘+’ and ’*’ operators for NumPy arrays:

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
a+b

array([5, 7, 9])

In [15]:
1.0*a/b


array([0.25, 0.4 , 0.5 ])

In [ ]:
1.3. Universal functions:

In [16]:
x = np.array([0, 1, 2, 3, 4, 5])

In [17]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [18]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [19]:
type(np.sqrt)

numpy.ufunc

In [20]:
type(np.exp)

numpy.ufunc

In [ ]:
1.4. NumPy functions:

In [25]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [26]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.median(a)

5.0

In [28]:
np.sum(a)

5485

In [29]:
np.round(np.var(a),2)

8.19

In [30]:
np.round(np.mean(a),2)

5.48

In [31]:
np.round(np.std(a),2)

2.86

In [32]:
np.max(a)

10

In [33]:
np.min(a)

1

In [ ]:
1.5. Statistical methods of NumPy arrays:

In [34]:
 x=np.arange(1,11)

In [35]:
x.sum()

55

In [36]:
 x.mean()

5.5

In [37]:
x.std()

2.8722813232690143

In [38]:
x.var()

8.25

In [39]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [40]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(y.mean(axis=0))

[4. 5. 6.]


In [42]:
print(y.mean(axis=1))

[2. 5. 8.]


In [44]:
z = np.random.randint(10,size=1000)

In [45]:
z.max()

9

In [46]:
z.min()

0

In [47]:
(z > 5).sum()

402

In [48]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [51]:
a.argmax()

4

In [52]:
a.argmin()

1