0.1.1 1. NumPy library:
1.1. NumPy basics:

In [1]:
 import numpy as np
np.__version__

'1.26.4'

In [2]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [8]:
arr3 = arr1

In [9]:
id(arr1)

1968195059024

In [10]:
id(arr3)

1968195059024

In [11]:
 arr4 = arr1.copy()

In [12]:
id(arr4)


1968244963728

1.2. Creating NumPy arrays: numpy.arange() function:

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [18]:
arr = np.arange(10)

In [19]:
 len(arr)

10

In [20]:
arr.size

10

numpy.linspace() function:

In [21]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
 arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [23]:
print(arr[0])
print(arr[1])

[ 0.   2.5  5.   7.5 10. ]
2.5


In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
 np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0], dtype=int64)

In [27]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [28]:
arr = np.ones((2,3), dtype ='int_')

In [29]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
arr.dtype

dtype('int32')

In [31]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [32]:
arr1 = np.array([111, 2.3, True, False, False])
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [33]:
arr2 = np.array([111, 2.3, 'python', 'abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [34]:
 arr3 = np.array([111, True, 'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U11')

1.3. Indexing and slicing NumPy arrays:

In [35]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [36]:
a[-1]

5

In [37]:
a[:]

array([1, 2, 3, 4, 5])

In [38]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a[1]

array([4, 5, 6])

In [40]:
a[-1]

array([7, 8, 9])

In [41]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a[2][1]

8

In [43]:
a[2,1]

8

In [44]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [45]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [46]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [47]:
arrMask = ( ( (arr % 5) == 0 ) & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [48]:
a.size

9

In [49]:
a.shape


(3, 3)

In [50]:
a.ndim

2

Change the shape with reshape() method:

In [51]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [55]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

In [56]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [57]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [58]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

1.5. Modifying NumPy arrays: Appending elements, rows and columns to arrays:

In [59]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [60]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [61]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:


In [62]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [65]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [66]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [67]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])