0.1.1 1. Correlation:

In [4]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

!wget --no-clobber https://raw.githubusercontent.com/stefannae/
↪SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/
↪SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv


In [5]:
 # Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [6]:
 # Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [7]:
df.shape

(150, 5)

In [8]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [10]:
# Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']
x
y

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

1.1. Pearson:


In [11]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)


array([0.872, 0.   ])

In [12]:
# Using the Pandas function.
x.corr(y)


0.8717537758865831

In [15]:
# Correlation array.
#np.round(df.corr(),3)
numeric_df = df.select_dtypes(include=[np.number])
correlation_matrix = np.round(numeric_df.corr(), 3)
correlation_matrix

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length         1.000       -0.118         0.872        0.818
Sepal.Width         -0.118        1.000        -0.428       -0.366
Petal.Length         0.872       -0.428         1.000        0.963
Petal.Width          0.818       -0.366         0.963        1.000

1.2. Spearman:

In [16]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

1.3. Kendall:

In [17]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)
# p-

array([0.719, 0.   ])

0.1.2 2. Interval Estimation of the Correl

!wget --no-clobber https://raw.githubusercontent.com/stefannae/
↪SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/
↪SIC_AI_Chapter_04_Coding_Exercises/data_studentli

In [19]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [20]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [24]:
# Set aside two variables.
x = df.height
y = df.weight

2.2. Confidence Interval of the Pearson Correlation:

In [25]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [26]:
# 95% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [28]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}